# Generated by Django 2.0.4 on 2019-03-15 02:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('monday', models.CharField(max_length=500, null=True)),
                ('tuesday', models.CharField(max_length=500, null=True)),
                ('wednesday', models.CharField(max_length=500, null=True)),
                ('thursday', models.CharField(max_length=500, null=True)),
                ('friday', models.CharField(max_length=500, null=True)),
                ('saturday', models.CharField(max_length=500, null=True)),
                ('sunday', models.CharField(max_length=500, null=True)),
                ('tickets', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=10)),
                ('population', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=100, null=True)),
                ('iso2', models.CharField(max_length=2, null=True)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoolKid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=2048)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.City')),
            ],
        ),
        migrations.CreateModel(
            name='CoolKidQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(default='', max_length=2048)),
                ('question', models.CharField(default='', max_length=2048)),
                ('answer', models.CharField(default='', max_length=2048)),
                ('coolKid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.CoolKid')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('short_description', models.CharField(default='', max_length=2048)),
                ('link', models.CharField(default='', max_length=2048)),
                ('image', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('tickets', models.TextField(default='')),
                ('timing', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('monday', models.CharField(max_length=500, null=True)),
                ('tuesday', models.CharField(max_length=500, null=True)),
                ('wednesday', models.CharField(max_length=500, null=True)),
                ('thursday', models.CharField(max_length=500, null=True)),
                ('friday', models.CharField(max_length=500, null=True)),
                ('saturday', models.CharField(max_length=500, null=True)),
                ('sunday', models.CharField(max_length=500, null=True)),
                ('tickets', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=1024, unique=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttractionMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserCityMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaygroundMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Playground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSourceMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(default='', max_length=128)),
                ('user_agent', models.TextField(default='')),
                ('country', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.User')),
            ],
        ),
    ]
