# Generated by Django 2.0.4 on 2019-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersourcemetric',
            name='country',
            field=models.CharField(db_index=True, default='', max_length=500),
        ),
    ]
