# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190419_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlogs',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='nomatch',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.Session'),
        ),
        migrations.AddField(
            model_name='nomatch',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.Session'),
        ),
    ]
